apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: patternfly-yew-demo-ou6a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: patternfly-yew-demo-ou6a
    app.kubernetes.io/part-of: patternfly-yew
  name: patternfly-yew-demo-ou6a
  namespace: jreimann-2-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: patternfly-yew-demo-ou6a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: patternfly-yew-demo-ou6a
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:1VcUD-patternfly-yew-demo-ou6a
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
