apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: patternfly-yew-demo-ou6a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: patternfly-yew-demo-ou6a
    app.kubernetes.io/part-of: patternfly-yew
  name: patternfly-yew-demo-ou6a
  namespace: jreimann-2-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: patternfly-yew-demo-ou6a
    weight: 100
status: {}
