apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: patternfly-yew-demo-ou6a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: patternfly-yew-demo-ou6a
    app.kubernetes.io/part-of: patternfly-yew
  name: patternfly-yew-demo-ou6a
  namespace: jreimann-2-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: patternfly-yew-demo-ou6a
status:
  loadBalancer: {}
